dataPath = 'training';
filelist = dir([dataPath filesep '*.jpg']);
trainImageList = cellfun(@(n) fullfile(dataPath,n), {filelist.name}', 'UniformOutput',false);
%{[dataPath,'training/001-1.jpg']%, ...
%                  [dataPath,'training/001-2.jpg'], ...
%                  [dataPath,'training/001-3.jpg'], ...
%                  [dataPath,'trainings/001-4.jpg']};%, ...
%                   [dataPath,'training/001-5.jpg'], ...
%                   [dataPath,'training/001-6.jpg'], ...
%                   [dataPath,'training/001-7.jpg'],...
%                   [dataPath,'training/002-1.jpg'],...
%                   [dataPath,'training/002-2.jpg'],...
%                   [dataPath,'training/002-3.jpg'],...
%                   [dataPath,'training/005-1.jpg'],...
%                   [dataPath,'training/005-2.jpg'],...
%                   [dataPath,'training/005-3.jpg'],...
%                   [dataPath,'training/005-4.jpg'],...
%                   [dataPath,'training/010-1.jpg'],...
%                   [dataPath,'training/010-2.jpg'],...
%                   [dataPath,'training/010-3.jpg'],...
%                   [dataPath,'training/020-1.jpg'],...
%                   [dataPath,'training/020-2.jpg'],...
%                   [dataPath,'training/020-3.jpg'],...
%                   [dataPath,'training/020-4.jpg'],...
%                   [dataPath,'training/050-1.jpg'],...
%                   [dataPath,'training/050-2.jpg'],...
%                   [dataPath,'training/050-3.jpg'],...
%                   [dataPath,'training/050-4.jpg'],...
%                   [dataPath,'training/100-1.jpg'],...
%                   [dataPath,'training/100-2.jpg'],...
%                   [dataPath,'training/100-3.jpg'],...
%                   [dataPath,'training/100-4.jpg'],...
%                   [dataPath,'training/200-1.jpg'],...
%                   [dataPath,'training/200-2.jpg'],...
%                   [dataPath,'training/200-3.jpg'],...
%                   [dataPath,'training/200-4.jpg'] 

testImageList =  {[dataPath,'test/00-1.jpg'], ...
                  [dataPath,'test/00-2.jpg'], ...
                  [dataPath,'test/00-3.jpg'], ...
                  [dataPath,'test/01-1.jpg'], ...
                  [dataPath,'test/01-2.jpg'], ...
                  [dataPath,'test/01-3.jpg'], ...
                  [dataPath,'test/01-4.jpg'], ...
                  [dataPath,'test/01-5.jpg'], ...
                  [dataPath,'test/01-6.jpg'], ...
                  [dataPath,'test/02-1.jpg'], ...
                  [dataPath,'test/02-2.jpg'], ...
                  [dataPath,'test/02-3.jpg'], ...
                  [dataPath,'test/02-4.jpg'], ... 
                  [dataPath,'test/03-1.jpg'], ...
                  [dataPath,'test/03-2.jpg'], ...
                  [dataPath,'test/03-3.jpg'], ...
                  [dataPath,'test/04-1.jpg'], ...
                  [dataPath,'test/04-2.jpg'], ...
                  [dataPath,'test/04-3.jpg'], ... 
                  [dataPath,'test/05-1.jpg'], ...
                  [dataPath,'test/05-2.jpg'], ...
                  [dataPath,'test/05-3.jpg'], ...
                  [dataPath,'test/06-1.jpg'], ...
                  [dataPath,'test/06-2.jpg'], ...
                  [dataPath,'test/06-3.jpg'], ...
                  [dataPath,'test/06-4.jpg'], ... 
                  [dataPath,'test/07-1.jpg'], ...
                  [dataPath,'test/07-2.jpg'], ...
                  [dataPath,'test/07-3.jpg'], ...
                  [dataPath,'test/08-1.jpg'], ...
                  [dataPath,'test/08-2.jpg'], ...
                  [dataPath,'test/08-3.jpg'], ...
                  [dataPath,'test/09-1.jpg'], ...
                  [dataPath,'test/09-2.jpg'], ...
                  [dataPath,'test/09-3.jpg'], ...
                  [dataPath,'test/10-1.jpg'], ...
                  [dataPath,'test/11-1.jpg'], ... 
                  [dataPath,'test/12-1.jpg']};
